#! /bin/sh
### BEGIN INIT INFO
# Provides:          zena
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init.d script to launch /usr/loca/bin/zena_init
### END INIT INFO

# Author: Gaspard Bucher <gaspard@teti.ch>
#

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="Zena server"

case "$1" in
  start)
        # launch ruby script
        /usr/local/bin/zena_init start
        ;;
  stop)
        # launch ruby script
        /usr/local/bin/zena_init start
        ;;
  restart)
        # launch ruby script
        /usr/local/bin/zena_init restart
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 3
        ;;
esac
