# frozen_string_literal: true
source "https://rubygems.org"

gem 'rails',          '2.3.18'

gem 'querybuilder',   :git=>'https://github.com/zena/querybuilder.git', :branch =>'2.2.1'
gem 'yamltest',       :git=>'https://github.com/zena/yamltest.git', :branch => '2.2.1'
gem 'safe_yaml'
gem 'rubyless',       :git=>'https://github.com/zena/rubyless.git', :branch=>'2.2.1'
gem 'property',       :git=>'https://github.com/zena/property.git', :branch=>'2.2.1-with-ar2.3.18'
gem 'versions',       :git=>'https://github.com/zena/versions.git', :branch => '2.2.1'

gem 'rake',						'10.1.1'
gem 'hpricot',				'0.8.6'
gem 'ruby-recaptcha', '1.0.3'
gem 'syntax',         '1.0.0'
gem 'tzinfo',					'1.2.2'
gem 'uuidtools',      '2.0.0'
#gem 'json',           '1.5.1'
gem 'yajl-ruby', require: 'yajl'
gem 'authlogic',      '2.1.11'
gem 'fast_gettext'    #,   '0.4.16'
gem	'gettext', 				'2.1.0'
gem 'will_paginate',  '2.3.12'
gem 'differ',         '0.1.2'
gem 'httparty',       '0.7.8'
gem 'httmultiparty', '0.3.8'
gem 'open4',					'1.3.4'
gem 'daemons',				'1.2.3'
gem 'gem_plugin',			'0.2.3'
gem 'simple_xlsx_writer',	'0.5.3'
gem 'RedCloth',				'3.0.4'
gem 'rubyzip',				'0.9.9'
gem 'public_suffix',  '1.3.3'
gem 'addressable', 		'2.3.8'
gem 'mysql',					'2.9.1'
gem 'rmagick',				'2.16.0'
gem 'rdoc',						'2.4.2'
gem 'iconv'
gem 'i18n'
gem 'syck'

group :test, :development do
	gem 'shoulda',        '2.10.3'
	gem 'test-unit'
	gem 'single_test', 		'~> 0.6.0'
end