#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

env, cmd = 'development', nil
ARGV.each do |arg|
  if arg =~ /RAILS_ENV\s*=\s*(\w+)/
    env = $1
  else
    cmd = arg
  end
end

unless %w{index start stop restart}.include?(cmd)
  puts "Usage: script/worker RAILS_ENV=production [start|stop|restart]"
  exit -1
end

dir = File.expand_path('.')

daemon_options = {
  :multiple   => false,
  :dir_mode   => :normal,
  :dir        => File.join(dir, 'log'),
  :backtrace  => true,
  # Create a worker.output to redirect STDOUT and STDERR
  :log_output => true,
}

ARGV.clear
ARGV << cmd

Daemons.run_proc('worker', daemon_options) do
  ARGV.clear

  Dir.chdir dir
  ENV['RAILS_ENV'] = RAILS_ENV = env
  require File.join('config', 'environment')

  require 'delayed/worker'
  begin
    require 'thinking_sphinx'
    require 'thinking_sphinx/deltas/delayed_delta'
  rescue LoadError
    # Ignore
  end

  puts "Starting worker..."

  Delayed::Worker.new.start
end
