set :application,         "example.org"
set :repository,          "svn://example.com/myapp/trunk"
set :apache2_ip,          "123.456.789.111"
set :mongrel_port,        "8000"
set :mongrel_count,       "3"
set :db_password,         "super secret password"
set :db_user,             "example_org"
