#!/usr/bin/env ruby

root     = File.join(File.dirname(__FILE__), '..')
svn_info = `svn info #{root.inspect} 2>&1 || svk info #{root.inspect} 2>&1`
if svn_info =~ %r{URL: svn://svn.zenadmin.org.*Revision: (\d+)}m
  rev = $1
else
  svk_info = `svk info #{root.inspect} 2>&1`
  if svk_info =~ %r{zenadmin.org/zena, Rev. (\d+)}m
    rev = $1
  elsif svk_info =~ %r{(Merged|Copied) From: (.*?), Rev}
    svk_info = `svk info /#{$2} 2>&1`
    if svk_info =~ %r{zenadmin.org/zena, Rev. (\d+)}m
      rev = $1
    else
      puts "revision number could not be found using svn or svk"
    end
  end
end

if rev
  version_file = File.read(File.join(root, 'config', 'version.rb'))
  File.open(File.join(root, 'config', 'version.rb'), 'wb') do |f|
    f.print  version_file.sub(/(REV *)=.*$/, "\\1= '#{rev}'")
  end
  puts "revision number updated to '#{rev}'"
end